spring:
  application:
    name: fratpos
  datasource:
    url: jdbc:mysql://localhost:3306/fratpos?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: fratpos
    initial-size: 1
    validation-query: SELECT 1
    test-on-borrow: true
    test-while-idle: true
