spring:
  aop:
    proxy-target-class: true
  application:
    name: fratpos
  datasource:
    url: jdbc:mysql://localhost:13306/fratpos?characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: fratpos
    password: fratpos
    initial-size: 1
    validation-query: SELECT 1
    test-on-borrow: true
    test-while-idle: true
  jpa:
    properties:
      hibernate.id.new_generator_mappings: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
preauth:
  principal: leola@leola.ee
  role: POS
  header: POS_USER
---

spring:
  profiles: flynn
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}/${MYSQL_DATABASE}?characterEncoding=UTF-8
    username: ${MYSQL_USER}
    password: ${MYSQL_PWD}

